- name: Deploy programapi generator with Nginx and Let's Encrypt SSL certificate
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    repository_url: https://github.com/EuroPython/programapi.git
    app_version: "{{ commit_hash }}"
    domain_name: programapi24.europython.eu

  tasks:
    - name: Install Docker dependencies
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release

    - name: Install Docker
      block:
        - name: Add Docker GPG key
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present

        - name: Add Docker repository
          apt_repository:
            repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
            state: present

        - name: Install Docker
          apt:
            name: docker-ce
            state: present

        - name: Add current user to docker group
          user:
            name: "{{ ansible_user }}"
            groups: docker
            append: yes
          changed_when: false

    - name: Clone repository to specific version (to a temporary location)
      git:
        repo: "{{ repository_url }}"
        dest: /tmp/repo
        version: "{{ app_version }}"

    - name: Copy latest src from repository clone to /srv
      command: cp -R /tmp/repo/src /srv

    - name: Copy Dockerfile
      command: cp /tmp/repo/Dockerfile /srv

    - name: Copy requirements.txt
      command: cp /tmp/repo/requirements.txt /srv

    - name: Copy Makefile
      command: cp /tmp/repo/Makefile /srv

    - name: Copy docker-compose.yml to the remote server
      ansible.builtin.template:
        src: ./docker-compose.yml.j2
        dest: /srv/docker-compose.yml

    - name: Copy Nginx configuration file
      ansible.builtin.template:
        src: ./nginx.conf.j2
        dest: /srv/nginx.conf

    - name: Copy Init-Letsencrypt
      ansible.builtin.template:
        src: ./init-letsencrypt.sh.j2
        dest: /srv/init-letsencrypt.sh

    - name: Sync pretalx data every 5 minutes
      ansible.builtin.cron:
        name: Sync pretalx data
        minute: "*/5"
        job: "cd /srv && docker compose run --rm app make all"

    - name: Do a system prune to avoid running out of disk space
      shell: "docker system prune -f"

    - name: Start Docker compose
      shell: "cd /srv && docker compose up -d --build --force-recreate"
