name: Deploy to static server

on:
  push:
    branches:
      - ep2023
  schedule:
    - cron: "*/10 * * * *" # every 10 minutes
  workflow_dispatch:

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Setup uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies from uv.lock
        run: make deps/install

      - name: Download data
        run: uv run make download > /dev/null 2>&1
        env:
            PRETALX_TOKEN: ${{ secrets.PRETALX_TOKEN }}

      - name: Transform data
        run: uv run make transform > /dev/null 2>&1

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Adjust known_hosts
        run: ssh-keyscan "static.europython.eu" > ~/.ssh/known_hosts

      - name: Deploy
        run: uv run make deploy FORCE_DEPLOY=true
